### ISSUE TITLE
Package fails to load

### ISSUE THREAD

**Issue by IainNZ** [kmsquire/XClipboard.jl#1]
http://status.julialang.org/

Does this package rely on X running to load? If so, I'd like to exclude this package from automated testing to avoid the "false negative".

**Comment by kmsquire** [comment]
It doesn't rely on X running to load, but it does immediately throw an error if libX11 is not found.

**Comment by kmsquire** [comment]
Looking at the source, I seem to be including a non-existent file!  I guess this package hasn't gotten much use... ;-)

(I'm pretty sure I forgot to add the file via git, but won't be able to fix it until tonight.)

**Comment by IainNZ** [comment]
Bump http://iainnz.github.io/packages.julialang.org/?pkg=XClipboard&ver=0.3

**Comment by kmsquire** [comment]
Thanks for the bump!  Again, I'll have to look at this tonight at home, where I developed it (and hopefully I'll remember this time).

**Comment by IainNZ** [comment]
Close for #2
